In [2]:
import requests
import pandas as pd
import os
import json

In [4]:
from baseline.setup.detectors.detect_method import DATA_PATH

In [5]:
base_url = "http://localhost:8000"

In [6]:
endpoint_up = "/file_info_store"
endpoint = "/detection"

In [7]:
path = os.path.abspath(os.path.join(DATA_PATH, "nasa", "dirty.csv"))
df = pd.read_csv(path, header="infer", encoding="utf-8", keep_default_na=False, low_memory=False)

In [8]:
shape = df.shape

In [10]:
detection_methods = ['Outlier detection (SD)']

In [11]:
from pydantic import BaseModel
from typing import List, Tuple
import numpy as np

In [12]:
class UploadReq(BaseModel):
    dirty_path: str
    dataset_name: str
    dataset_shape: Tuple[int,int]

In [13]:
class DetectionRequest(BaseModel):
    detection_methods: List[str]

In [14]:
data = UploadReq(dirty_path=path, dataset_name='nasa', dataset_shape=shape).dict()

In [43]:
response = requests.post(base_url + endpoint_up, json=data)

In [44]:
if response.status_code == 200:
    print("Request succeeded!")
else:
    print("Request failed!")

Request succeeded!


In [18]:
response.text

'{"message":"Dataset stored successfully"}'

In [19]:
detReqData = DetectionRequest(detection_methods=detection_methods).dict()

In [42]:
response2 = requests.post(base_url + endpoint, json=detReqData)

In [35]:
if response2.status_code == 200:
    print("Request succeeded!")
else:
    print("Request failed!")

Request succeeded!


In [22]:
response_json = response2.json()

In [23]:
error_array = np.array(response_json)

In [24]:
error_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
for element in error_array:
    if np.isin(1, element):
        print(element)

[0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 1.]
